<?php

namespace MC12\SubscriptionBundle\Repository;

/**
 * CategoryMarkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryMarkingRepository extends \Doctrine\ORM\EntityRepository
{
}
