<?php

namespace MC12\SubscriptionBundle\Repository;

/**
 * DriveLicenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriveLicenceRepository extends \Doctrine\ORM\EntityRepository
{
}
