<?php

namespace MC12\SubscriptionBundle\Repository;

/**
 * MarkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkingRepository extends \Doctrine\ORM\EntityRepository
{
}
