<?php

namespace MC12\SubscriptionBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends EntityRepository
{

    public function findAllByRaceId($id)
    {
        return $this->createQueryBuilder('m')
            ->from('MC12SubscriptionBundle:Meal', 'meal')
            ->join('meal.stage', "s")
            ->join('s.race', 'race')
            ->where('race.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
