# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        MC12\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:    ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login
            remember_me:
              secret: '%secret%'
        admin:
            pattern: ^/admin
            anonymous: false
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }


