services:
#    mc12_core.example:
#        class: MC12\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    mc12_core.services.mailer:
        class: MC12\CoreBundle\Service\Mailer
        arguments:
            - "@mailer"
            - "@twig"
